name: Unittest deep-code

on:
  push:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout deep-code
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Install deep-code in editable mode
        shell: bash -l {0}
        run: |
          cd /home/runner/work/deep-code/deep-code
          pip install -e ".[dev]" 

      - name: Lint with ruff
        run: |
            pip install ruff
            ruff check

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          cd /home/runner/work/deep-code/deep-code
          pytest --cov=deep_code --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: deepesdl/deep-code

